<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="DESKTOP-ISNDRDG" failures="1" tests="1" name="Gemys_Task" time="19.353" errors="0" timestamp="2022-04-29T02:13:29 EET">
  <testcase classname="testcases.CreateAnAccountTests" name="createValidAccount" time="8.514">
    <failure type="java.lang.AssertionError" message="The account does&amp;apos;t created successfully expected [My account - My Store] but found [Login - My Store]">
      <![CDATA[java.lang.AssertionError: The account does't created successfully expected [My account - My Store] but found [Login - My Store]
at helper.Assertions.assertOnPage(Assertions.java:14)
at testcases.CreateAnAccountTests.createValidAccount(CreateAnAccountTests.java:57)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- createValidAccount -->
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="0.0">
    <ignored/>
  </testcase> <!-- runScenario -->
</testsuite> <!-- Gemys_Task -->
